name: Destroy Terraform Code

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - dev
      - uat


jobs:
  create-infra:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-central-1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      - run: echo "ðŸ¤–Destroying  ${{  github.head_ref }}."

      - name: "Setup Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: "Test S3"
        run: aws s3 ls s3://apmechev-tfm-remote-state

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - run: ls
      - run: which python
      - run: which python3

      - name: "Terraform Init"
        run: terraform init
      
      - name: Get Branch Name
        run: |
          if [ ! -z "${{ github.head_ref }}" ];
             then echo "BRANCH=$(echo ${{ github.head_ref }}| awk -F/ '{print $NF}')" >> $GITHUB_ENV; echo "Running inside PR from branch ${{ github.head_ref }}"; 
             else echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/}| awk -F/ '{print $NF}')" >> $GITHUB_ENV; echo "Running inside branch $(echo ${GITHUB_REF#refs/heads/})"
          fi
          echo
      - name: "Select Workspace"
        run: |
          if [ -z $( terraform workspace list | grep ${{ env.BRANCH }} ) ]; then terraform workspace new ${{ env.BRANCH }}; fi
          terraform workspace select ${{ env.BRANCH }}
  
      - name: "Terraform Plan"
        run: terraform plan -var="branch_name=${{ env.BRANCH }}" -var="SECRET_KEY=${{ secrets.CAKEDAYS_SECRET_KEY }}"

      - name: "Terraform Destroy"
        run: terraform destroy -var="branch_name=${{ env.BRANCH }}" -var="SECRET_KEY=${{ secrets.CAKEDAYS_SECRET_KEY }}" -auto-approve

      - name: "Delete Workspace"
        run: terraform workspace select default; terraform workspace delete ${{ env.BRANCH }}
